name: Seatly CI/CD

on:
  push:
    branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - uses: actions/flutter-action@v2
          with:
            channel: 'stable'
        - run: flutter pub get
        - run: flutter pub run build_runner build --delete-conflicting-outputs

    test:
      runs-on: ubuntu-latest
      needs: build

      steps:
        - uses: actions/checkout@v3
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
        - run: flutter pub get
        - run: flutter pub run build_runner build --delete-conflicting-outputs
        - run: flutter test --coverage
        - name: Upload coverage
          uses: actions/upload-artifact@v3
          with:
            name: coverage-report
            path: coverage/lcov.info

# build-android:
#   runs-on: ubuntu-latest
#   needs: build
#
#   steps:
#     - uses: actions/checkout@v3
#     - uses: actions/flutter-action@v2
#       with:
#         channel: 'stable'
#     - run: flutter pub get
#     - run: flutter build apk --split-per-abi
#     - name: Upload APK
#       uses: actions/upload-artifact@v3
#       with:
#         name: android-apk
#         path: build/app/outputs/flutter-apk/
#
# build-ios:
#   runs-on: macos-latest
#   needs: build
#
#   steps:
#     - uses: actions/checkout@v3
#     - uses: actions/flutter-action@v2
#       with:
#         channel: 'stable'
#     - run: flutter pub get
#     - run: flutter build ios --no-codesign
#     - name: Upload iOS
#       uses: actions/upload-artifact@v3
#       with:
#         name: ios-ipa
#         path: build/ios/iphoneos/*.ipa

# create-release:
#   runs-on: ubuntu-latest
#   needs: [ build-android, build-ios ]
#   steps:
#     - uses: actions/checkout@v3
#     - name: Create Release
#       uses: softprops/action-gh-release@v1
#       with:
#         files: |
#           build/app/outputs/flutter-apk/*.apk
#           build/ios/iphoneos/*.ipa
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# deploy-android:
#   runs-on: ubuntu-latest
#   needs: create-release
#
#   steps:
#     - uses: actions/checkout@v3
#     - name: Deploy to Google Play
#       uses: r0adkll/upload-google-play@v1
#       with:
#         serviceAccountJson: ${{ secrets.GOOGLE_PLAY_JSON }}
#         packageName: 'com.example.seatly'
#         releaseFile: 'build/app/outputs/flutter-apk/app-release.apk'
#
# deploy-ios:
#   runs-on: : macos-latest
#   needs: create-release
#
#   steps:
#     - uses: actions/checkout@v3
#     - name: Deploy to App store
#       uses: apple-actions/app-store-connect@v2
#       with:
#         apiKeyId: ${{ secrets.APPLE_API_KEY_ID }}
#         apiKeyIssuerId: ${{ secrets.APPLE_API_ISSUER_ID }}
#         apiPrivateKey: ${{ secrets.APPLE_API_PRIVATE_KEY }}
#         bundleId: 'com.example.seatly'
#         ipaPath: 'build/ios/iphoneos/*.ipa'